name: Checks
on:
  push:
    branches:
      - master
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git
          ./target
        key: "${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}"
        restore-keys: ${{ runner.os }}-cargo-
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: cargo install --force cargo-tarpaulin cargo-audit
    - run: cargo generate-lockfile
    - run: cargo audit
    - run: cargo check --workspace --all-features
      env:
        RUSTFLAGS: --deny warnings
    - run: cargo fmt --all -- --check
    - run: cargo clippy --workspace --all-features -- --deny warnings
    - run: cargo test --workspace --all-features
    - run: cargo +nightly tarpaulin --packages ups --all-features --fail-under 70
    - run: cargo doc --workspace --all-features
