name: Checks
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v9
      with:
        name: rust-ups
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell ci.nix --run "export RUSTFLAGS='--deny warnigns'; cargo check --workspace --all-features"
    - run: nix-shell ci.nix --run "cargo fmt --workspace --all-features -- --check"
    - run: nix-shell ci.nix --run "cargo clippy --workspace --all-features -- --deny warnings"
    - run: nix-shell ci.nix --run "cargo test --workspace --all-features"
    - run: nix-shell ci.nix --argstr channel nightly --run "cargo tarpaulin --package ups --all-features --fail-under 70"
    - run: nix-shell ci.nix --run "cargo doc --workspace --all-features"
